#version 430

#pragma optimize(on)

layout(local_size_x = {LocalSizeX}) in;

struct ShaderConfig {
    int particleCount;
    float dt;
    float sigma2;
    float clampVel;
    float clampAcc;
    float fieldSize;
    float cellSize;
    float maxDist;
    int speciesCount;
    float damping;
    int trackedIdx;
    float maxForce;
    float amp;
    int cellCount;
    int totalCellCount;
    ivec4 disabled[4];
};

struct Particle
{
   vec4 position;
   vec4 velocity;
   int species;
   int flags;
   int  cellIndex;
   float xzAngle;
   float yAngle;
   int _pad0;
   int _pad1;
   int _pad2;
};

#define MAX_SPECIES_COUNT     10
#define KEYPOINTS_COUNT       6
#define FORCE_COUNT           (MAX_SPECIES_COUNT * MAX_SPECIES_COUNT * KEYPOINTS_COUNT)

layout(std140, binding = 0) uniform ConfigBuffer {
    ShaderConfig config;
};

layout(std430, binding = 1) readonly buffer InputBuffer
{
    Particle inParticles[];
};

layout(std430, binding = 2) writeonly buffer OutputBuffer
{
    Particle outParticles[];
};

layout(std430, binding = 4) readonly buffer ForceBuffer {
    vec4 forces[];
};

layout(std430, binding = 5) writeonly buffer TrackingBuffer
{
    Particle tracked;
};

layout(std430, binding = 6) buffer CellCount {
    uint cellCounts[];
};

layout(std430, binding = 7) buffer CellOffsets {
    uint cellOffsets[];
};

layout(std430, binding = 8) buffer ParticleIndices {
    uint particleIndices[];
};

void torus_pos(inout vec4 pos)
{
    if (pos.x >= config.fieldSize)
        pos.x -= config.fieldSize;
    else if (pos.x < 0)
        pos.x += config.fieldSize;

    if (pos.y >= config.fieldSize)
        pos.y -= config.fieldSize;
    else if (pos.y < 0)
        pos.y += config.fieldSize;

    if (pos.z >= config.fieldSize)
        pos.z -= config.fieldSize;
    else if (pos.z < 0)
        pos.z += config.fieldSize;
}

void torus_dist(inout vec4 d)
{
    if (abs(d.x) > config.fieldSize / 2)
        d.x -= config.fieldSize*sign(d.x);

    if (abs(d.y) > config.fieldSize / 2)
        d.y -= config.fieldSize*sign(d.y);

    if (abs(d.z) > config.fieldSize / 2)
        d.z -= config.fieldSize*sign(d.z);
}

float evaluateForceForOffset(uint offset, float dist)
{
    // Clamp distance to valid range
    dist = clamp(dist, forces[offset].x, forces[offset+5].x);

    // Find the segment [i, i+1] that contains dist
    for (int i = 0; i < KEYPOINTS_COUNT-1; ++i)
    {
        float x0 = forces[offset+i].x;
        float x1 = forces[offset+i + 1].x;

        if (dist <= x1)
        {
            float t = (dist - x0) / (x1 - x0);
            return mix(forces[offset+i].y, forces[offset+i + 1].y, t);
        }
    }

    // Safety fallback (should never happen)
    return 0.0;
}

vec4 compute_single_acceleration(vec4 sensorPos, Particle p, Particle other)
{
    vec4 d = other.position - sensorPos; 
    torus_dist(d);
    vec4 single_acc = vec4(0,0,0,0);
    if (abs(d.x) <= config.maxDist && abs(d.y) <= config.maxDist && abs(d.z) <= config.maxDist)
    {
        float r2 = dot(d, d) + config.sigma2;
        float r = sqrt(r2);
        uint forceOffset = (p.species * MAX_SPECIES_COUNT + other.species) * KEYPOINTS_COUNT;
        float f = evaluateForceForOffset(forceOffset, r);
        single_acc = config.amp * f * d / r;
    }

    return single_acc;
}

int wrapCell(int c)
{
    return (c % config.cellCount + config.cellCount) % config.cellCount;
}

vec4 compute_total_acceleration(vec4 sensorPos, uint idx, Particle p)
{
    int cellCount2 = config.cellCount * config.cellCount;
    int gridX = p.cellIndex % config.cellCount;
    int gridY = (p.cellIndex / config.cellCount) % config.cellCount;
    int gridZ = p.cellIndex / (cellCount2);
    ivec3 main = ivec3(gridX, gridY, gridZ);

    vec4 acc = vec4(0.0);
    for (int dz = -1; dz <= 1; dz++)
    for (int dy = -1; dy <= 1; dy++)
    for (int dx = -1; dx <= 1; dx++)
    {
        ivec3 cell = main + ivec3(dx, dy, dz);
        cell.x = wrapCell(cell.x);
        cell.y = wrapCell(cell.y);
        cell.z = wrapCell(cell.z);
        uint cellIdx = cell.x +
                       cell.y * config.cellCount +
                       cell.z * cellCount2;
        uint offset = cellOffsets[cellIdx];
        uint count = cellCounts[cellIdx];
        for(uint indiceIdx = offset; indiceIdx<offset + count; indiceIdx++)
        {
            uint otherIdx = particleIndices[indiceIdx];
            if (idx != otherIdx)
            {
                 Particle other = inParticles[otherIdx];
                 acc += compute_single_acceleration(sensorPos, p, other);
            }
        }
    }

    return acc;
}

void update_one(uint idx)
{
    Particle p = inParticles[idx];
    
    
    vec4 vel = p.velocity;
    vec4 pos = p.position;
    float xzAngle = p.xzAngle;
    float yAngle = p.yAngle;
    vec4 sensorDir = vec4(0);
    sensorDir.x = cos(yAngle) * sin(xzAngle);
    sensorDir.y = sin(yAngle);
    sensorDir.z = cos(yAngle) * cos(xzAngle);
    sensorDir = normalize(sensorDir);
    vec4 sensorPos = pos + 15 * sensorDir;

    vec4 acc = compute_total_acceleration(sensorPos, idx, p);

    vec3 direction = vec3(0);
    direction.x = cos(yAngle) * sin(xzAngle);
    direction.y = sin(yAngle);
    direction.z = cos(yAngle) * cos(xzAngle);
    vec3 d = normalize(direction);

    float k = 0.1;

    vec3 a = acc.xyz;
    vec3 a_perp = a - d * dot(d, a);
    d = normalize(d + k * a_perp * config.dt);

    xzAngle = atan(d.x, d.z);
    yAngle  = atan(d.y, length(vec2(d.x, d.z)));


    vel.x = cos(yAngle) * sin(xzAngle);
    vel.y = sin(yAngle);
    vel.z = cos(yAngle) * cos(xzAngle);



    //integrate position
    pos += vel * config.dt;

    torus_pos(pos);

    //prepare updated particle struct
    p.xzAngle = xzAngle;
    p.yAngle = yAngle;
    p.position = pos;
    p.velocity = vel;
    p.flags = 0;
    if (config.trackedIdx > -1 && config.trackedIdx == idx)
    {
        p.flags = 1;
        tracked = p;
    }

    bool isDisabled = config.disabled[p.species / 4][p.species % 4] != 0;
    if (isDisabled)
        p.flags = 2;

    outParticles[idx] = p;
}

void main()
{
    uint idx = gl_GlobalInvocationID.x;
    if (idx >=0 && idx < config.particleCount) 
    {
        update_one(idx);
    }
}